spring:
  application:
    name: myspringboot
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1214
    url: jdbc:mysql://192.168.3.195:3306/learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: muwentao
mybatis:
  type-aliases-package: com.mwt.demo.entity
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml



server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 8081
com:
  mwt:
    title: mwt
    description:  this is  learn springboot way


#thymeleaf
logging:
  file:
    path: D:/log

